name: 8 Update itaEvents

on:
  workflow_dispatch:

permissions:
  contents: write    # Per poter pushare i file modificati in repo
  actions: write     # Per gestire i workflow
  pull-requests: write

jobs:
  update-files:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install requests pytz
          python -m pip install --upgrade pip
          pip install beautifulsoup4 playwright bs4 lxml rapidfuzz python-dateutil python-dotenv webdriver-manager pillow
          pip install python-dotenv

      - name: Run extract_schedule.py
        run: |
          python extract_schedule.py

      - name: Run itaevents.py
        run: |
          python itaevents.py

      - name: Run fullita.py
        run: |
          python fullita.py

      - name: Run mpdenv.py
        run: |
          python mpdenv.py

      - name: Run mergelists.py
        run: |
          python mergelists.py \
            channels_italy.m3u8 \
            247ita.m3u8 \
            calcio_playlist.m3u8 \
            sportstreaming_playlist.m3u8 \
            sportzone.m3u8

      # ───────────────────────────────────────────────────────────────────────────────
      # NUOVO STEP: ordina_listone.py (deduplica e ordina listone.m3u8)
      - name: Resa eseguibile ordina_listone.py
        run: chmod +x ordina_listone.py

      - name: Ordina e deduplica listone.m3u8
        run: |
          ./ordina_listone.py
      # ───────────────────────────────────────────────────────────────────────────────

      - name: Run epg.py
        run: |
          python epg.py

      - name: Commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          # Se ci sono modifiche (include ora listone_ordinato.m3u8), vengono committate
          if [[ -n $(git status --porcelain) ]]; then
            git commit -m "Update Itaevents $(date +%H:%M)"
            git pull --rebase origin main
            git push
          else
            echo "No changes to commit"
          fi
