name: 8 Update itaEvents

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  contents: write
  actions: write
  pull-requests: write

jobs:
  update-files:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests pytz beautifulsoup4 bs4 lxml rapidfuzz python-Levenshtein python-dateutil python-dotenv webdriver-manager pillow chardet
          python -m pip install playwright
          python -m playwright install chromium

      - name: Pulisci file JSON esistenti
        run: |
          rm -f daddyliveSchedule.json
          echo "File JSON eliminati per garantire dati freschi"

      - name: Run script extract_schedule
        run: |
          python extract_schedule.py

      - name: Run script itaevents.py e fullita.py
        run: |
          python itaevents.py
          python fullita.py

      - name: Run script mpdenv.py
        run: |
          python mpdenv.py

      # CORREZIONE APPLICATA QUI
      - name: Run script mergelists.py
        run: |
          python mergelists.py \
            "channels_italy.m3u8" \
            "247ita.m3u8" \
            "calcio_playlist.m3u8" \
            "sportstreaming_playlist.m3u8" \
            "sportzone.m3u8"

      - name: Resa eseguibile ordina_listone.py
        run: chmod +x ordina_listone.py

      - name: Ordina e deduplica listone.m3u8
        run: |
          ./ordina_listone.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          if [[ -n $(git status --porcelain) ]]; then
            git commit -m "Update Itaevents $(date +%H:%M)"
            git pull --rebase origin main
            git push
          else
            echo "No changes to commit"
          fi
